site_name: KTH Digital Research Handbook
site_url: https://docs.datarepository.kth.se/
repo_url: https://github.com/KTH-Library/docs-kth-rdm
copyright: '© 2025 KTH Royal Institute of Technology'

extra_css:
  - stylesheets/extra.css
theme:
  name: material
  font:
    text: Figtree
  logo: assets/images/kth-logo.svg
  favicon: assets/images/favicon.ico
  features:
    - navigation.tabs

  palette:
    - scheme: slate
      primary: custom
    # dark theme
      toggle:
        icon: material/brightness-7
        name: Dark mode
      accent: pink

    # light theme
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Light mode
      primary: custom
      accent: pink

# https://squidfunk.github.io/mkdocs-material/reference/code-blocks/?h=code#configuration
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true

# Footer
extra:
  generator: false
  social:
    - icon: simple/github
      link: https://github.com/KTH-Library/docs-kth-rdm
validation:
# https://www.mkdocs.org/user-guide/configuration/#validation
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

plugins:
  - search:
      lang: en
      # https://squidfunk.github.io/mkdocs-material/plugins/search/#config.pipeline
      pipeline:
        - stemmer
        - stopWordFilter
        - trimmer
  # https://ultrabug.github.io/mkdocs-static-i18n/getting-started/quick-start/
  # https://github.com/squidfunk/mkdocs-material/discussions/2346
  - i18n:
      # https://ultrabug.github.io/mkdocs-static-i18n/setup/setting-up-search/
      reconfigure_search: true
      # Can be 'folder' or 'suffix' e.g index.sv.md
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true

        - locale: sv
          name: Svenska
          build: true
          # Nav Translations
          # https://ultrabug.github.io/mkdocs-static-i18n/setup/localizing-navigation/
          nav:
            - Hem: sv/index.md
            - Guider:
                - Snabbstart: get_started/quick_start.md
                - Skapa ett konto: get_started/create_account.md
                - Logga in och logga ut: get_started/login_logout.md
                - Visa inloggade enheter: get_started/viewing-devices.md
                - Navigera i KTH Data Repository: get_started/navigating_site.md
                - Sökning på metadatafält: get_started/metadata_field_searches.md
            - Om:
                - Villkor för användning: terms.md
                - Cookies Policy: cookie-policy.md

nav:
  # When updating the nav, remember to update the i18n plugin nav as well
  - Home: index.md
  - Guides:
      - Quick Start: get_started/quick_start.md
      - Create an Account: get_started/create_account.md
      - Logging in and Logging out: get_started/login_logout.md
      - View Logged in Devices: get_started/viewing-devices.md
      - Navigating the KTH Data Repository: get_started/navigating_site.md
      - Metadata Field Searches: get_started/metadata_field_searches.md
  - About:
      - Terms of Use: terms.md
      - Cookies Policy: cookie-policy.md
